// app/components/SearchBar.vue
<template lang="pug">
div(class="w-full mx-auto")
  div(class="relative")
    div(class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none")
      svg(
        aria-hidden="true",
        class="w-5 h-5 text-gray-500",
        fill="none",
        stroke="currentColor",
        viewBox="0 0 24 24",
        xmlns="http://www.w3.org/2000/svg"
      )
        path(
          stroke-linecap="round",
          stroke-linejoin="round",
          stroke-width="2",
          d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
        )
    input(
      type="search",
      :value="modelValue",
      @input="$emit('update:modelValue', $event.target.value)",
      class="block w-full py-2 pr-2 md:py-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all duration-300 shadow-sm hover:shadow-md",
      placeholder="Fan art HashTag Search",
      required
    )
</template>

<script setup>
defineProps(['modelValue'])
defineEmits(['update:modelValue'])
</script>

// src/components/SearchBar.svelte
<script>
  export let value = '';
</script>

<div class="w-full mx-auto">
  <div class="relative">
    <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
      <svg aria-hidden="true" class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
      </svg>
    </div>
    <input
      type="search"
      bind:value
      on:input
      class="block w-full py-2 pr-2 md:py-4 pl-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 outline-none transition-all duration-300 shadow-sm hover:shadow-md"
      placeholder="Fan art HashTag Search"
      required
    />
  </div>
</div>
